### ISSUE TITLE
Doesn't seem to work on new versions of Cinnamon

### ISSUE THREAD

**Issue by nick-s-b** [lestcape/Garbage-Collector#2]
Hi,
After the upgrade to latest versions of Cinnamon, this applet doesn't show any values anymore. I've checked the log and I see these error messages:

````
error t=2017-09-10T17:55:52.492Z global.get_memory_info is not a function
trace t=2017-09-10T17:55:52.492Z 
<----------------
MyApplet.prototype.get_memory_info@/home/fate/.local/share/cinnamon/applets/garbageCollector@lestcape/applet.js:215:21
MyApplet.prototype._on_alarm_setup@/home/fate/.local/share/cinnamon/applets/garbageCollector@lestcape/applet.js:178:21
---------------->
error t=2017-09-10T17:56:04.565Z global.get_memory_info is not a function
trace t=2017-09-10T17:56:04.565Z 
<----------------
MyApplet.prototype.get_memory_info@/home/fate/.local/share/cinnamon/applets/garbageCollector@lestcape/applet.js:215:21
MyApplet.prototype._on_alarm_setup@/home/fate/.local/share/cinnamon/applets/garbageCollector@lestcape/applet.js:178:21
bind/<@resource:///org/cinnamon/cjs/modules/lang.js:95:16
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:573:40
---------------->
error t=2017-09-10T17:56:06.973Z global.get_memory_info is not a function
trace t=2017-09-10T17:56:06.973Z 
<----------------
MyApplet.prototype.get_memory_info@/home/fate/.local/share/cinnamon/applets/garbageCollector@lestcape/applet.js:215:21
MyApplet.prototype._on_alarm_setup@/home/fate/.local/share/cinnamon/applets/garbageCollector@lestcape/applet.js:178:21
bind/<@resource:///org/cinnamon/cjs/modules/lang.js:95:16
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:573:40
---------------->
error t=2017-09-10T17:56:07.474Z global.get_memory_info is not a function
trace t=2017-09-10T17:56:07.474Z 

````

Any easy fixes for this function call? Looks like devs changed it to something else...
Thanks!

**Comment by lestcape** [comment]
Hi @nick-s-b, yes sorry, probably is because they updated cjs to be working with a much more recently Firefox core. I don't used cinnamon anymore, so i don't know really what happen and i can not fix it without use cinnamon. 

See: all the extensions that I have created are discontinued. This one is not the exception, but just this is not really an utility to users, is more like an utility to detect and force the garbage collector to clean up more often the garbage (preventing him to stop working when it should work).

It can not fixed the memory leak really, always occurs because a human error in some places (not necessary the cinnamon code). So, this just force the cinnamon garbage collector to be more active. Then this just can fixed the specific case of not call the garbage collector when should be called, and of course it's not called because a human error.
